version: 2
jobs:
  build:
    working_directory: ~/theoziran/secreth_telegrambot
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: ~/theoziran/secreth_telegrambot/test-reports
      CIRCLE_TEST_REPORTS: $CIRCLE_ARTIFACTS
    docker:
    - image: circleci/python:3.6-jessie-node-browsers-legacy
      command: /sbin/init
    steps:
    - checkout
    - run: 
        name: Install test dependencies
        command: | 
                sudo pip install --upgrade pip
                sudo pip install pathlib
                sudo pip install pytest
                pip install --user -r requirements-dev.txt
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        # This is a broad list of cache paths to include many possible development environments
        # You can probably delete some of these entries
        - src
    - run:
        name: Run the tests
        command: |
                mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
                ./test.sh ci
    - store_test_results:
        path: test-reports
    - store_artifacts:
        path: test-reports
  deploy:
    machine:
        enabled: true
    working_directory: ~/theoziran/secreth_telegrambot
    parallelism: 1
    shell: /bin/bash --login
    steps:
    - checkout
    - run:
        name: Deploy
        command: './deploy.sh'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
              - build
          filters:
              branches:
                  only: master
      - deploy:
          requires:
              - hold
          filters:
              branches:
                  only: master

